require("plugins.plugins")
require("cmp.cmp")
require("env-setting")
require("keybinds")
require("lsp-config")
require("statusline")
require("markdown-preview")
require("telescope.telescope")
require("themes")
require("todo-comments.todo-comments")
require("tree-sitter")
require("nvim-tree.nvim-tree")
require("luasnip.luasnip")
require("neorg.neorg")
require("vimtex")
require("telescope.telescope")
require("mason").setup()
require("getgit.getgit")
-- require('chtsh').setup({
--     lang = { 'python' }
-- })
