require("plugins.plugins")
require("toggle_term")
require("indent_blankline.indent")
require("nvim_tree")
require("env_setting")
require("keybinds")
require("markdown_preview")
require("lua_line")
require("buffer_line")
require("telescope.telescope")
require("todo_comments")
require("cmp.cmp")
require("lsp_config")
require("tree_sitter")
require("themes")
require("ultisnips")

