require("lsp_config.server_settings.pyright")
require("lsp_config.server_settings.tsserver")
require("lsp_config.server_settings.sumneko_lua")
require("lsp_config.server_settings.marksman")
require("lsp_config.server_settings.html")
require("lsp_config.server_settings.cssls")
require("lsp_config.server_settings.jsonls")
