require("lsp-config.server.pyright")
require("lsp-config.server.tsserver")
require("lsp-config.server.sumneko_lua")
require("lsp-config.server.marksman")
require("lsp-config.server.cpp")
require("lsp-config.server.go")
require("lsp-config.server.bash")
require("lsp-config.server.jsonls")
